### ISSUE TITLE
Error in receiving webhook events to EventListener

### ISSUE THREAD

**Issue by nkottary** [JuliaWeb/GitHub.jl#125]
I get the following error on the server on recieving the webhook ping event from github.com:

```
┌ Error: error handling request
│   exception =
│    MethodError: no method matching (::getfield(GitHub, Symbol("##165#167")){GitHub.OAuth2,String,Array{String,1},typeof(Main.Registrator.RegServer.event_handler)})(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}})
│    Closest candidates are:
│      #165(!Matched::HTTP.Messages.Request) at /home/nkottary/.julia/packages/GitHub/Y0gpt/src/activity/events.jl:79
│    Stacktrace:
│     [1] macro expansion at /home/nkottary/.julia/packages/HTTP/GN0Te/src/Servers.jl:352 [inlined]
│     [2] (::getfield(HTTP.Servers, Symbol("##13#14")){getfield(GitHub, Symbol("##165#167")){GitHub.OAuth2,String,Array{String,1},typeof(Main.Registrator.RegServer.event_handler)},HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}})() at ./task.jl:259
```

 I am running the server like this:

```
listener = GitHub.EventListener(event_handler;
                                auth=GitHub.authenticate("***"),
                                secret="***",
                                events=["ping", "pull_request", "push"])
GitHub.run(listener, ip"0.0.0.0", 8090)
```

**Comment by KristofferC** [comment]
Seems like the wrong argument is being passed to this function:

https://github.com/JuliaWeb/GitHub.jl/blob/f250009fdbfeabd90fd1150600ca9ef0d9dfd831/src/activity/events.jl#L79-L82

@quinnj any idea what could cause this?

**Comment by nkottary** [comment]
Seems to be an issue with HTTP.jl. I downgraded to 0.7.1 from 0.8.0 and it works now.

**Comment by quinnj** [comment]
What's the actual HTTP.jl call here? I can't seem to tell where HTTP.jl comes into play.

**Comment by quinnj** [comment]
What thing that might be happening is the difference between `HTTP.listen` and `HTTP.serve`; `listen` is for lower-level server functionality that operates directly on `HTTP.Stream`, where the handler must read/write the request/response themselves. `HTTP.serve` is higher-level and can operate on `HTTP.Stream` or `HTTP.Request` or any other `HTTP.Handler` type that can handle streams/requests. So if you're calling `HTTP.listen` with a handler that expects `HTTP.Request`, it should just be a matter of switching to `HTTP.serve`.
