### ISSUE TITLE
Question: can/should this repo be used as a template for wrapping API's in Julia?

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaWeb/GitHub.jl#153]
I am trying to convert a bunch of libraries I used in Python to Julia. This involves wrapping some API's which I have never done before. Can I use the bones of this repo as an example for the other API's?

**Comment by simonbyrne** [comment]
Yes, basically people have been adding the APIs that they need as they go along.

**Comment by logankilpatrick** [comment]
This also helped me a lot! https://stackoverflow.com/questions/59010720/how-to-make-a-request-to-a-specific-url-in-julia
