### ISSUE TITLE
Authentication method used is deprecated.

### ISSUE THREAD

**Issue by KristofferC** [JuliaWeb/GitHub.jl#156]
I got the following email:

---
Hi @KristofferC,

On February 5th, 2020 at 09:21 (UTC) your personal access token (.........) using GitHub-jl was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team

----

It seems this has to be updated here.

**Comment by fredrikekre** [comment]
Looks like https://github.com/JuliaWeb/GitHub.jl/blob/cfe6b07246e20962e05ba7a77ee63ac057b88948/src/utils/auth.jl#L56. In other places the Authentication header is used via https://github.com/JuliaWeb/GitHub.jl/blob/cfe6b07246e20962e05ba7a77ee63ac057b88948/src/utils/auth.jl#L65-L80
