### ISSUE TITLE
Needs test

### ISSUE THREAD

**Issue by malmaud** [JuliaWeb/GitHub.jl#40]
Since this is in JuliaWeb, it would be good to get its testing up to par with the other packages in the org.

So:
* [ ] Actually get some tests in runtests.jl 
* [ ] Including AppVeyor testing
* [ ] Collect testing coverage and link to it from the README

**Comment by jrevels** [comment]
Yeah, see #7.

I plan on doing a big testing sweep next week after [this other stuff](https://github.com/JuliaWeb/GitHub.jl/compare/master...jrevels:jr/all) gets merged.

**Comment by jrevels** [comment]
I've been whittling away on this for the past week, and coverage is around 70% now (with line-by-line results showing that most of the important stuff is tested), so I'm going to consider this closed.
