### ISSUE TITLE
Bring back the old `repo` constructor `repo(owner, repname)`?

### ISSUE THREAD

**Issue by IainNZ** [JuliaWeb/GitHub.jl#45]
I noticed this was removed (breaking the PkgEval website code), but I wasn't sure what the logic was

**Comment by jrevels** [comment]
You should use the new form [`repo(repo_name)`](https://github.com/JuliaWeb/GitHub.jl#repositories). For example, this:

```
repo("JuliaWeb", "GitHub.jl")
```

should now be written like this:

```
repo("JuliaWeb/GitHub.jl") # the repo's full_name property
```

The logic is that I [should either be able to pass in a `GitHub.Repo` *or* the repo's name into any API methods that require repository information](https://github.com/JuliaWeb/GitHub.jl#response-types). This one-to-one mapping between string identifiers and GitHubTypes makes things much easier to reason about API-wise, and eliminates the need for duplicated code/messy dispatch handling.

**Comment by jrevels** [comment]
Providing clearer documentation of that one-to-one mapping in the GitHubType table would probably help; I'll go ahead and do that today.

**Comment by IainNZ** [comment]
Yeah I figured out the fix, but I like the logic
